baseURL = 'https://oridem.salorak.es/'
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
theme = "hugo-theme-relearn"
canonifyURLs = true
relativeURLs = true

[params]
alwaysopen = true
collapsibleMenu = false
author.name = "Mario Acosta & Hector Alarcon"
showVisitedLinks = false
themeVariant = ["zen-dark", "zen-light"]
disableLandingPageButton = true


# Multilenguages
[languages]
[languages.es]
title = "Orientacion Academica"
weight = 1
languageName= "Español"
languageCode = 'es'
disabled = false

[languages.cat]
title = "Orientació Académica"
weight = 2 
languageName= "Catala"
languageCode = 'cat'
disabled = false
