defaultContentLanguage = "es"
theme = "hugo-theme-relearn"
baseURL = 'https://oridem.salorak.es/'

[params]
alwaysopen = true
collapsibleMenu = false
author.name = "Mario Acosta & Hector Alarcon"
showVisitedLinks = false
themeVariant = [ "zen-light", "relearn-light"]
disableLandingPageButton = true

# Multilanguages
[languages]
[languages.es]
title = "Oridem"
weight = 1
languageName= "Español"
languageCode = "es"
disabled = false

[languages.cat]
title = "Orientació Académica"
weight = 2 
languageName= "Catala"
languageCode = "cat"
disabled = true 
